# Copyright (c) 2026 MCTV Digital, Inc. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution,
# or modification of this file is strictly prohibited.
"""Serve the public non-Streamlit pages.

Routes installed here:

  GET /rates              the self-serve rate calculator (static/rates.html)
  GET /board/<slug>       a Real Estate Feeds Board  (static/board.html)
  GET /board/<slug>.json  that board's render payload (Supabase-backed)

Streamlit exposes no routing API, so this reaches into the web server it
boots and inserts routes ahead of Streamlit's catch-all (which otherwise
answers /rates with the app shell). Two stacks are handled because
Streamlit is mid-migration from Tornado to Starlette/uvicorn and which one
runs depends on the version pip resolves at image build time:

  * Tornado   - a RequestHandler at the head of the wildcard router
  * Starlette - a wrapper around the ASGI app handed to uvicorn

Both patches follow the same rule as the ones in app.py: they reach into
private innards, so each is guarded on its own and none of them are
allowed to stop the app from booting. The calculator stays reachable at
/app/static/rates.html regardless (Streamlit's own static serving, see the
SAFE_APP_STATIC_FILE_EXTENSIONS patch in app.py), so a patch that stops
matching a future Streamlit degrades to a longer URL, not a missing page.

The board split -- static shell at /board/<slug>, data at
/board/<slug>.json -- exists so the HTML can be cached and the panel can
re-poll just the payload. It also keeps this module's request path free of
database work for the shell: if Supabase is down, the board still loads and
keeps rendering whatever it last held.

install() has to run BEFORE the server starts - i.e. from run_server.py.
Patches applied from app.py run too late, the routes are already built.
"""

import json
import logging
import re
from pathlib import Path

_STATIC = Path(__file__).parent / "static"

# Trailing slash is stripped before comparing, so /rates and /rates/ both hit.
RATES_PATH = "/rates"
RATES_FILE = _STATIC / "rates.html"
BOARD_FILE = _STATIC / "board.html"

CACHE_CONTROL = "public, max-age=300"
# The payload carries live listings and a rate whose staleness rule is
# enforced server-side, so it gets a much shorter leash than the shell.
JSON_CACHE_CONTROL = "public, max-age=60"

# Slugs are generated by board_service.slugify(), which emits [a-z0-9-].
# Anchored and character-classed so this can never walk the filesystem.
BOARD_RE = re.compile(r"^/board/([a-z0-9][a-z0-9-]{0,80})(\.json)?$")

_page_cache: dict[str, bytes] = {}


def _file_bytes(path: Path) -> bytes:
    """Read a static page off disk once and hold it in memory."""
    key = str(path)
    if key not in _page_cache:
        _page_cache[key] = path.read_bytes()
    return _page_cache[key]


def _board_json(slug: str) -> bytes | None:
    """Render payload for a board, or None when it doesn't exist.

    Imported lazily and caught broadly on purpose: this runs inside the web
    server's request path, and a Supabase hiccup must degrade to a 503 for
    one board rather than taking the process down.
    """
    try:
        from services.board_service import render_payload
        payload = render_payload(slug)
    except Exception as exc:  # noqa: BLE001 - see docstring
        logging.warning("board %s: payload build failed (%s)", slug, exc)
        return None
    if payload is None:
        return None
    return json.dumps(payload).encode("utf-8")


def _resolve(path: str, method: str) -> tuple[int, str, bytes] | None:
    """Map a request to (status, content_type, body), or None to fall through.

    Shared by both server stacks so their behaviour cannot drift.
    """
    if method not in ("GET", "HEAD"):
        return None

    trimmed = path.rstrip("/") or "/"

    if trimmed == RATES_PATH:
        try:
            return 200, "text/html; charset=utf-8", _file_bytes(RATES_FILE)
        except OSError as exc:
            logging.warning("rate calculator: %s unreadable (%s)", RATES_FILE, exc)
            return None

    match = BOARD_RE.match(trimmed)
    if match:
        slug, is_json = match.group(1), match.group(2)
        if is_json:
            body = _board_json(slug)
            if body is None:
                return 404, "application/json", b'{"error":"board not found"}'
            return 200, "application/json", body
        try:
            return 200, "text/html; charset=utf-8", _file_bytes(BOARD_FILE)
        except OSError as exc:
            logging.warning("board: %s unreadable (%s)", BOARD_FILE, exc)
            return None

    return None


def _cache_header(content_type: str) -> str:
    return JSON_CACHE_CONTROL if content_type.startswith("application/json") \
        else CACHE_CONTROL


def _install_tornado() -> None:
    import tornado.web
    from streamlit.web.server import server as st_server

    class PublicPageHandler(tornado.web.RequestHandler):
        def get(self):
            resolved = _resolve(self.request.path, "GET")
            if resolved is None:
                raise tornado.web.HTTPError(404)
            status, content_type, body = resolved
            self.set_status(status)
            self.set_header("Content-Type", content_type)
            self.set_header("Cache-Control", _cache_header(content_type))
            self.write(body)

        head = get

        def check_xsrf_cookie(self):
            # Public pages, no cookie to check.
            pass

    original_create_app = st_server.Server._create_app

    def _create_app(self):
        app = original_create_app(self)
        router = app.wildcard_router
        rules = [
            (r"/rates/?", PublicPageHandler),
            (r"/board/[^/]+/?", PublicPageHandler),
        ]
        router.add_rules(rules)
        # add_rules appends; Streamlit's catch-all is already in the list,
        # so the new rules only win if we move them to the front.
        for _ in rules:
            router.rules.insert(0, router.rules.pop())
        return app

    st_server.Server._create_app = _create_app


def _wrap_asgi(app):
    if not callable(app):  # uvicorn also accepts "module:attr" strings
        return app

    async def public_pages_asgi(scope, receive, send):
        if scope.get("type") == "http":
            resolved = _resolve(scope.get("path", ""), scope.get("method", ""))
            if resolved is not None:
                status, content_type, body = resolved
                await send({
                    "type": "http.response.start",
                    "status": status,
                    "headers": [
                        (b"content-type", content_type.encode()),
                        (b"content-length", str(len(body)).encode()),
                        (b"cache-control", _cache_header(content_type).encode()),
                    ],
                })
                await send({
                    "type": "http.response.body",
                    "body": b"" if scope["method"] == "HEAD" else body,
                })
                return

        await app(scope, receive, send)

    return public_pages_asgi


def _install_asgi() -> None:
    import uvicorn

    original_init = uvicorn.Config.__init__

    def __init__(self, app, *args, **kwargs):
        original_init(self, _wrap_asgi(app), *args, **kwargs)

    uvicorn.Config.__init__ = __init__


def install() -> None:
    """Register the public routes on whichever server Streamlit is about to boot."""
    if not RATES_FILE.exists():
        logging.warning("public pages: %s missing, /rates not installed", RATES_FILE)
    if not BOARD_FILE.exists():
        logging.warning("public pages: %s missing, /board not installed", BOARD_FILE)
    if not RATES_FILE.exists() and not BOARD_FILE.exists():
        return

    for stack, patch in (("Tornado", _install_tornado), ("ASGI", _install_asgi)):
        try:
            patch()
            logging.info("public pages: routes installed on the %s server", stack)
        except ImportError:
            logging.info("public pages: %s server not present, skipping", stack)
        except Exception as exc:
            logging.warning(
                "public pages: could not install routes on the %s server (%s) - "
                "calculator still served at /app/static/rates.html", stack, exc,
            )
