"""Host Media Kit proposal generator for venue partners.

Generates a branded media kit for potential host venues (restaurants, bars,
salons, etc.) explaining the free advertising benefits of hosting an MCTV
screen and the available add-on packages.
"""

from generators.base_proposal import BaseProposal
from services.config_service import get_team_member, get_all_tiers
from services.docx_service import NAVY, GOLD, GRAY, Pt, WD_ALIGN_PARAGRAPH


class HostMediaKitProposal(BaseProposal):
    """Generates a Host Media Kit proposal for prospective venue partners."""

    @property
    def proposal_type_key(self) -> str:
        return "host_media_kit"

    def get_sections(self) -> list:
        return [
            ("opportunity", "The Opportunity"),
            ("host_benefits", "Host Benefits"),
            ("_host_package", "Your Free Host Package"),
            ("_addon_pricing", "Add-On Advertising Packages"),
            ("_network_locations", "MCTV Network Locations"),
            ("getting_started", "Let's Get Started"),
            ("_team", "Meet Your Team"),
        ]

    def get_prompt_variables(self, data) -> dict:
        rep = get_team_member(self.config, data.sales_rep)
        return {
            "venue_name": data.venue_name,
            "contact_name": data.contact_name,
            "venue_category": data.venue_category,
            "city": data.city,
            "proposed_screen_count": data.proposed_screen_count,
            "free_outside_screens": data.free_outside_screens,
            "host_free_screens": data.free_outside_screens,
            "sales_rep": rep["name"],
            "additional_notes": data.additional_notes or "No additional notes.",
        }

    def _build_cover(self, doc, input_data):
        """Build cover page with 'Host Media Kit' title."""
        rep = get_team_member(self.config, input_data.sales_rep)
        self.docx.add_cover_page(
            doc,
            title="Host\nMedia Kit",
            subtitle="PARTNERSHIP OVERVIEW",
            prepared_for=f"{input_data.contact_name} \u2014 {input_data.venue_name}",
            prepared_by=rep,
        )

    def build_section(self, doc, section_key, data, content):
        if section_key == "opportunity":
            self._build_opportunity(doc, data, content)
        elif section_key == "host_benefits":
            self._build_host_benefits(doc, content)
        elif section_key == "_host_package":
            self._build_host_package(doc, data)
        elif section_key == "_addon_pricing":
            self._build_addon_pricing(doc, data)
        elif section_key == "_network_locations":
            self._build_network_locations(doc)
        elif section_key == "getting_started":
            self._build_getting_started(doc, data, content)
        elif section_key == "_team":
            self.docx.add_team_section(doc)

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _build_opportunity(self, doc, data, content):
        """The Opportunity section with network stats banner."""
        self.docx.add_section_header(doc, "The Opportunity")
        self.docx.add_body_text(doc, content)

        network = self.config["network"]
        self.docx.add_metrics_banner(doc, {
            network["total_screens"]: "Screens Across\nNorth Mississippi",
            network["monthly_impressions"]: "Monthly Impressions",
            f"{network['avg_dwell_time_minutes']}+ Min": "Avg. Dwell Time\nPer Visit",
            f"{network['plays_per_hour']}x/Hour": "Ad Plays\nEvery Hour",
        })
        doc.add_page_break()

    def _build_host_benefits(self, doc, content):
        """Host Benefits section generated by Claude."""
        self.docx.add_section_header(doc, "Host Benefits")
        self.docx.add_body_text(doc, content)
        doc.add_page_break()

    def _build_host_package(self, doc, data):
        """Config-driven free host package breakdown."""
        self.docx.add_section_header(doc, "Your Free Host Package")

        pricing = self.config["pricing"]
        inside_plays = pricing["host_free_inside_plays_per_hour"]
        outside_plays = pricing["host_outside_plays_per_hour"]
        free_outside = data.free_outside_screens

        # Calculate monthly ad plays
        # Inside: plays/hr * hours/day * days/month * screens at this venue
        hours_per_day = 12  # typical operating hours
        days_per_month = 30
        inside_monthly = inside_plays * hours_per_day * days_per_month * data.proposed_screen_count
        outside_monthly = outside_plays * hours_per_day * days_per_month * free_outside
        total_monthly = inside_monthly + outside_monthly

        self.docx.add_sub_header(doc, "AT YOUR LOCATION")
        self.docx.add_body_text(
            doc,
            f"Your ad plays {inside_plays}x per hour on "
            f"{'every screen' if data.proposed_screen_count == 1 else f'all {data.proposed_screen_count} screens'} "
            f"at {data.venue_name}. That means your business is front and center "
            f"for every customer who walks through the door \u2014 all day, every day, at no cost."
        )

        self.docx.add_sub_header(doc, "ACROSS THE MCTV NETWORK")
        self.docx.add_body_text(
            doc,
            f"As a host venue, {data.venue_name} also receives FREE advertising "
            f"on {free_outside} additional screens across the MCTV network at "
            f"{outside_plays}x per hour. Your brand reaches customers at restaurants, "
            f"gyms, barbershops, and more \u2014 people who may have never visited your location."
        )

        # Summary metrics banner
        self.docx.add_metrics_banner(doc, {
            f"{inside_plays}x/hr": f"At {data.venue_name}",
            f"{free_outside}": "Additional Screens\nAcross the Network",
            f"{outside_plays}x/hr": "At Each\nNetwork Location",
            f"{total_monthly:,}": "Total Ad Plays\nPer Month",
        })

        self.docx.add_body_text(
            doc,
            f"Total value: {total_monthly:,} ad plays every month at absolutely no cost to you."
        )
        doc.add_page_break()

    def _build_addon_pricing(self, doc, data):
        """Config-driven add-on pricing tiers with host discount note."""
        self.docx.add_section_header(doc, "Add-On Advertising Packages")

        self.docx.add_body_text(
            doc,
            f"Want even more exposure? As an MCTV host venue, {data.venue_name} "
            f"gets preferred pricing on expanded advertising packages. Add more "
            f"screens to amplify your reach across Oxford, Starkville, and Tupelo."
        )

        # Standard tiers table
        tiers = get_all_tiers(self.config)
        self.docx.add_pricing_table(doc, tiers)

        self.docx.add_sub_header(doc, "HOST VENUE ADVANTAGE")
        self.docx.add_body_text(
            doc,
            "As a host partner, you already have premium placement at your own "
            "location at no charge. Any add-on package stacks on top of your "
            "free host benefits \u2014 giving you more total exposure than a "
            "standard advertiser at the same price point."
        )

        # Contract terms
        self.docx.add_sub_header(doc, "PARTNERSHIP TERMS")
        self.docx.add_contract_terms(doc, self.config)
        doc.add_page_break()

    def _build_network_locations(self, doc):
        """Config-driven network locations summary."""
        self.docx.add_section_header(doc, "MCTV Network Locations")

        self.docx.add_body_text(
            doc,
            "MCTV Elite Advertising operates the largest indoor digital billboard "
            "network in North Mississippi. Here is where your ads can play:"
        )

        markets = self.config["markets"]
        for market_name, market_data in markets.items():
            screens = market_data["screens"]
            status = market_data["status"]
            description = market_data.get("description", "")

            if status == "active":
                self.docx.add_sub_header(doc, f"{market_name.upper()} \u2014 {screens} SCREENS")
                self.docx.add_body_text(doc, description)
            elif status == "expanding":
                self.docx.add_sub_header(doc, f"{market_name.upper()} \u2014 COMING SOON")
                self.docx.add_body_text(doc, description)

        # Venue categories
        self.docx.add_sub_header(doc, "WHERE YOUR ADS PLAY")
        self.docx.add_venue_categories(doc)
        doc.add_page_break()

    def _build_getting_started(self, doc, data, content):
        """Getting Started section with contact card."""
        self.docx.add_section_header(doc, "Let's Get Started")
        self.docx.add_body_text(doc, content)

        rep = get_team_member(self.config, data.sales_rep)
        self.docx.add_sub_header(doc, "YOUR PARTNERSHIP CONTACT")

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(rep["name"])
        run.font.size = Pt(14)
        run.font.bold = True
        run.font.color.rgb = NAVY

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(f"{rep['email']}\n{rep['phone']}")
        run.font.size = Pt(11)
        run.font.color.rgb = GRAY

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("MCTV Elite Advertising  |  MCTVofMS.com")
        run.font.size = Pt(10)
        run.font.color.rgb = GOLD

        doc.add_page_break()
