# Copyright (c) 2026 MCTV Digital, Inc. All rights reserved.
# Proprietary and confidential. Unauthorized copying, distribution,
# or modification of this file is strictly prohibited.
"""Terms of Service and Privacy Policy for MCTV Client Portal."""

import streamlit as st

st.set_page_config(page_title="Terms of Service - MCTV", page_icon="📋", layout="wide")

# Hide sidebar for public page
st.markdown("""
<style>
    [data-testid="stSidebar"] { display: none; }
    [data-testid="stSidebarCollapsedControl"] { display: none; }
</style>
""", unsafe_allow_html=True)

st.markdown("## MCTV Elite Advertising — Terms of Service")
st.caption("Last Updated: February 24, 2026")

st.divider()

st.markdown("""
### 1. Acceptance of Terms

By accessing or using the MCTV Elite Advertising platform ("Platform"), including the client
portal, proposal tools, reporting dashboards, and related services, you agree to be bound by
these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform.

### 2. Description of Service

MCTV Digital, Inc. ("MCTV," "we," "us," or "our") provides a digital advertising management
platform that enables:
- Generation and delivery of advertising proposals
- Digital contract execution and management
- Invoice tracking and payment management
- Creative asset submission and review
- Campaign performance reporting
- SMS and email communications related to your advertising account

### 3. Account Registration and Security

- You are responsible for maintaining the confidentiality of your login credentials
- You must provide accurate and current contact information
- You must notify MCTV immediately of any unauthorized access to your account
- MCTV reserves the right to suspend or terminate accounts that violate these Terms

### 4. Intellectual Property

**MCTV's Property:** The Platform, including all software, code, designs, layouts, algorithms,
prompt templates, report formats, proposal templates, branding elements, and documentation, is
the exclusive intellectual property of MCTV Digital, Inc. and is protected by copyright, trade
secret, and other intellectual property laws.

**Your Content:** You retain ownership of any photos, logos, graphics, or text content you upload
to the Platform. By uploading content, you grant MCTV a non-exclusive license to use that content
solely for the purpose of creating and displaying your advertisements on the MCTV network.

**Generated Materials:** Proposals, reports, contracts, and other documents generated by the
Platform on your behalf are provided for your use in connection with your MCTV advertising
partnership. You may not reverse-engineer, decompile, or attempt to extract the underlying
templates, algorithms, or processes used to generate these materials.

### 5. Acceptable Use

You agree not to:
- Attempt to access, copy, or extract the Platform's source code, algorithms, or proprietary processes
- Share your login credentials with unauthorized third parties
- Use the Platform for any purpose other than managing your MCTV advertising account
- Upload malicious files, viruses, or harmful content
- Attempt to interfere with the Platform's operation or security
- Scrape, crawl, or automatically extract data from the Platform

### 6. Electronic Signatures

The Platform supports electronic contract execution. By typing your name and checking the
agreement box on a contract, you acknowledge that:
- Your electronic signature is legally binding under the Mississippi Uniform Electronic
  Transactions Act (Miss. Code Ann. 75-12-1 et seq.) and the federal E-SIGN Act
- You have reviewed the contract terms before signing
- Your signature carries the same legal weight as a handwritten signature

### 7. SMS Communications

If you opt in to receive SMS messages from MCTV:
- Message frequency varies based on your account activity
- Message and data rates may apply
- You may opt out at any time by replying STOP to any message
- MCTV complies with the Telephone Consumer Protection Act (TCPA) and requires documented
  consent before sending any text messages

### 8. Privacy and Data Protection

**Data We Collect:** Contact information (name, email, phone, business address), advertising
account details, uploaded creative assets, contract and invoice records, and Platform usage data.

**How We Use It:** Solely to manage your MCTV advertising account, generate proposals and
reports, process contracts and invoices, and communicate about your account.

**Data Sharing:** We do not sell, rent, or share your personal information with third parties
except as necessary to operate the Platform (e.g., Supabase for data storage, Twilio for SMS
delivery) or as required by law.

**Data Security:** We use industry-standard security measures including encrypted connections,
access controls, row-level security policies, and environment-level secrets management.

**Data Retention:** Your account data is retained for the duration of your advertising
partnership and for a reasonable period afterward for legal and accounting purposes. You may
request deletion of your data by contacting your MCTV representative.

### 9. Payment Terms

- Invoices are generated based on your advertising contract terms
- Payment is due by the date specified on each invoice
- Overdue invoices may incur late fees as specified in your contract
- MCTV reserves the right to suspend advertising services for accounts with unpaid invoices
  exceeding 60 days past due

### 10. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, MCTV DIGITAL, INC. SHALL NOT BE LIABLE FOR ANY
INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF
THE PLATFORM. MCTV'S TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID FOR ADVERTISING
SERVICES IN THE 12 MONTHS PRECEDING THE CLAIM.

### 11. Disclaimer of Warranties

THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE." MCTV MAKES NO WARRANTIES, EXPRESS OR
IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
NON-INFRINGEMENT. MCTV DOES NOT GUARANTEE SPECIFIC ADVERTISING RESULTS, IMPRESSION COUNTS,
OR CAMPAIGN PERFORMANCE OUTCOMES.

### 12. Indemnification

You agree to indemnify and hold harmless MCTV Digital, Inc. and its owners, officers, and
employees from any claims, losses, or damages arising from your use of the Platform, your
uploaded content, or your violation of these Terms.

### 13. Governing Law

These Terms are governed by the laws of the State of Mississippi. Any disputes shall be resolved
in the courts of Hinds County, Mississippi.

### 14. Changes to Terms

MCTV reserves the right to modify these Terms at any time. We will notify you of material
changes through the Platform or via email. Continued use of the Platform after such notice
constitutes acceptance of the updated Terms.

### 15. Contact Information

**MCTV Digital, Inc.**
Oxford, Mississippi

- **Creed Cannon** — Managing Partner — creed@mctvofms.com
- **Mary Michael Cannon** — Managing Partner — mmc@mctvofms.com
- **Swayze Hollingsworth** — Director of Sales — swayze@mctvofms.com

Website: www.mctvofms.com
""")

st.divider()
st.caption("Copyright (c) 2026 MCTV Digital, Inc. All rights reserved.")
